import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { Command } from "commander";
import {
  findProjectRoot,
  literalMatchesAllTokens,
  literalMatchesAnyToken,
  loadCodeMap,
  loadMemoriesFromDir,
  memoryMatchesAnchorPaths,
  queryCodeMap,
  resolveHaivePaths,
  tokenizeQuery,
  trackReads,
} from "@hiveai/core";
import { ui } from "../utils/ui.js";

interface BriefingOptions {
  task?: string;
  files?: string;
  symbols?: string;
  maxMemories?: string;
  scope?: string;
  includeDraft?: boolean;
  includeStale?: boolean;
  dir?: string;
}

export function registerBriefing(program: Command): void {
  program
    .command("briefing")
    .description(
      "Print project context + relevant memories in one shot — ideal for agent onboarding",
    )
    .option("--task <text>", "what you are about to do — filters memories by relevance")
    .option("--files <csv>", "comma-separated file paths being worked on (anchors memories)")
    .option("--symbols <csv>", "symbol names to look up in the code-map (e.g. PaymentService,TenantFilter)")
    .option("--max-memories <n>", "cap on memories surfaced", "10")
    .option(
      "--scope <scope>",
      "personal | team | module | all (default: team)",
      "team",
    )
    .option("--include-draft", "include draft memories (excluded by default)")
    .option("--include-stale", "include stale memories (excluded by default — may be outdated)")
    .option("-d, --dir <dir>", "project root")
    .action(async (opts: BriefingOptions) => {
      const root = findProjectRoot(opts.dir);
      const paths = resolveHaivePaths(root);

      if (!existsSync(paths.memoriesDir)) {
        // No memories yet — just print project context and exit
        if (existsSync(paths.projectContext)) {
          console.log(`${ui.bold("=== Project Context ===")}\n`);
          console.log((await readFile(paths.projectContext, "utf8")).trim());
        } else {
          ui.warn("No project-context.md found. Run `haive init` and the `bootstrap_project` MCP prompt to set it up.");
        }
        return;
      }

      const all = await loadMemoriesFromDir(paths.memoriesDir);
      const filePaths = parseCsv(opts.files);
      const tokens = opts.task ? tokenizeQuery(opts.task) : null;
      const maxMemories = Math.max(1, Number(opts.maxMemories ?? 10));
      const scopeFilter = opts.scope ?? "team";

      // ── 1. Session recap — always shown first so agents start with fresh context ──
      const recaps = all
        .filter(({ memory: mem }) => mem.frontmatter.type === "session_recap")
        .sort((a, b) =>
          new Date(b.memory.frontmatter.created_at).getTime() -
          new Date(a.memory.frontmatter.created_at).getTime(),
        );
      if (recaps.length > 0) {
        const recap = recaps[0]!;
        const fm = recap.memory.frontmatter;
        const rev = fm.revision_count ? ` · revision #${fm.revision_count}` : "";
        console.log(`${ui.bold("=== Last Session Recap ===")}\n`);
        console.log(ui.dim(`${fm.id} (${fm.scope}${rev})`));
        console.log(recap.memory.body.trim());
        console.log();
      }

      // ── 2. Project context ─────────────────────────────────────────────────────
      if (existsSync(paths.projectContext)) {
        const ctx = await readFile(paths.projectContext, "utf8");
        const isTemplate = ctx.includes("TODO — high-level overview") || ctx.includes("Generated by `haive init`");
        if (isTemplate) {
          ui.warn(
            "project-context.md still contains the default template — get_briefing will return little value.",
          );
          ui.warn(
            "Fix: in your AI client, invoke the MCP prompt bootstrap_project to auto-fill it from your codebase.",
          );
          console.log();
        } else {
          console.log(`${ui.bold("=== Project Context ===")}\n`);
          console.log(ctx.trim());
          console.log();
        }
      } else {
        ui.warn(
          "No project-context.md found. Run `haive init` then invoke the bootstrap_project MCP prompt.",
        );
      }

      // Filter: exclude noise, drafts, stale, and session_recap (shown above) by default
      const candidates = all.filter(({ memory: mem }) => {
        const fm = mem.frontmatter;
        if (fm.status === "rejected" || fm.status === "deprecated") return false;
        if (!opts.includeDraft && fm.status === "draft") return false;
        if (!opts.includeStale && fm.status === "stale") return false;
        if (scopeFilter !== "all" && fm.scope !== scopeFilter) return false;
        if (fm.type === "session_recap") return false; // shown separately above
        return true;
      });

      // Score by relevance (AND on task tokens; OR fallback if AND produces no task hits)
      const andTaskHits = tokens
        ? new Set(candidates.filter(({ memory: mem }) => literalMatchesAllTokens(mem, tokens)).map(({ memory: mem }) => mem.frontmatter.id))
        : null;
      const useOrFallback = andTaskHits !== null && andTaskHits.size === 0 && (tokens?.length ?? 0) > 1;

      const scored = candidates.map(({ memory: mem, filePath }) => {
        const fm = mem.frontmatter;
        let score = 0;
        if (fm.status === "validated") score += 3;
        else if (fm.status === "proposed") score += 1;
        if (filePaths.length > 0 && memoryMatchesAnchorPaths(mem, filePaths)) score += 4;
        if (tokens) {
          if (andTaskHits?.has(fm.id)) score += 3;
          else if (useOrFallback && literalMatchesAnyToken(mem, tokens)) score += 1;
        }
        return { memory: mem, filePath, score };
      });

      scored.sort((a, b) => b.score - a.score);
      const top = scored.slice(0, maxMemories);

      if (top.length === 0) {
        ui.info("No relevant memories found.");
        const draftCount = all.filter(
          (m) =>
            m.memory.frontmatter.status === "draft" &&
            (scopeFilter === "all" || m.memory.frontmatter.scope === scopeFilter),
        ).length;
        if (draftCount > 0) {
          ui.info(`(${draftCount} draft memories excluded — use --include-draft to show)`);
        }
        return;
      }

      console.log(`${ui.bold("=== Relevant Memories ===")}\n`);
      for (const { memory: mem } of top) {
        const fm = mem.frontmatter;
        const badge = ui.statusBadge(fm.status);
        const draftMarker = fm.status === "draft" ? ui.yellow(" [DRAFT]") : "";
        const unverifiedMarker = fm.status === "proposed" ? ui.yellow(" [UNVERIFIED]") : "";
        console.log(
          `${ui.bold(fm.id)}  ${ui.dim(fm.scope + "/" + fm.type)}  ${badge}${draftMarker}${unverifiedMarker}`,
        );
        console.log(mem.body.trim());
        console.log();
      }
      console.log(ui.dim(`${top.length} memor${top.length === 1 ? "y" : "ies"} surfaced`));

      // Track reads so usage stats, decay, and hot-memory detection work via CLI too
      const ids = top.map(({ memory: mem }) => mem.frontmatter.id);
      if (ids.length > 0) {
        await trackReads(paths, ids).catch(() => { /* non-fatal */ });
      }

      // ── Code-map symbol lookup ──────────────────────────────────────────
      const requestedSymbols = (opts.symbols ?? "")
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      if (requestedSymbols.length > 0) {
        const codeMap = await loadCodeMap(paths);
        if (!codeMap) {
          ui.warn("No code-map found. Run `haive index code` first to enable symbol lookup.");
        } else {
          console.log(`\n${ui.bold("=== Symbol Locations ===")}\n`);
          for (const sym of requestedSymbols) {
            const { files } = queryCodeMap(codeMap, { symbol: sym });
            if (files.length === 0) {
              console.log(`${ui.dim(sym)}  (not found in code-map)`);
            } else {
              for (const f of files) {
                const exports = f.entry.exports.filter((e) =>
                  e.name.toLowerCase().includes(sym.toLowerCase()),
                );
                for (const e of exports) {
                  const desc = e.description ? `  — ${e.description}` : "";
                  console.log(`${ui.bold(e.name)}  ${ui.dim(f.path + ":" + e.line)}  [${e.kind}]${desc}`);
                }
              }
            }
          }
          console.log();
        }
      }
    });
}

function parseCsv(value: string | undefined): string[] {
  if (!value) return [];
  return value.split(",").map((s) => s.trim()).filter(Boolean);
}
