import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { Command } from "commander";
import { findProjectRoot, resolveHaivePaths } from "@hiveai/core";
import { ui } from "../utils/ui.js";

const PROJECT_CONTEXT_TEMPLATE = `# Project context

> Generated by \`haive init\`. Edit this file (or let your AI agent fill it via the upcoming MCP \`bootstrap_project\` tool).

## Architecture
TODO — high-level overview of the codebase.

## Key modules
TODO — list main modules and their purpose.

## Conventions
TODO — coding conventions, naming, patterns the team follows.

## Glossary
TODO — domain terms and what they mean here.

## Gotchas
TODO — known traps, surprising behavior, things newcomers stub their toes on.
`;

const BRIDGE_BODY = `<!-- hAIve bridge file — do not edit by hand. -->
<!-- This file points your AI tool at the shared hAIve project context. -->

See \`.ai/project-context.md\` for the full project context.
Memories live under \`.ai/memories/\` (personal/team/module).
`;

export function registerInit(program: Command): void {
  program
    .command("init")
    .description("Initialize a hAIve project (.ai/ structure + bridge files)")
    .option("-d, --dir <dir>", "project root", process.cwd())
    .option("--no-bridges", "do not generate CLAUDE.md / .cursorrules / copilot-instructions.md")
    .action(async (opts: { dir: string; bridges: boolean }) => {
      const root = path.resolve(opts.dir);
      const paths = resolveHaivePaths(root);

      if (existsSync(paths.haiveDir)) {
        ui.warn(`.ai/ already exists at ${paths.haiveDir} — leaving existing files in place.`);
      }

      await mkdir(paths.personalDir, { recursive: true });
      await mkdir(paths.teamDir, { recursive: true });
      await mkdir(paths.moduleDir, { recursive: true });
      await mkdir(paths.modulesContextDir, { recursive: true });

      if (!existsSync(paths.projectContext)) {
        await writeFile(paths.projectContext, PROJECT_CONTEXT_TEMPLATE, "utf8");
        ui.success(`Created ${path.relative(root, paths.projectContext)}`);
      }

      if (opts.bridges) {
        await writeBridge(root, "CLAUDE.md");
        await writeBridge(root, ".cursorrules");
        await writeBridge(root, path.join(".github", "copilot-instructions.md"));
      }

      ui.success(`hAIve initialized at ${root}`);
      ui.info("Next: " + ui.bold("haive memory add --type convention --slug <name>"));
    });
}

async function writeBridge(root: string, relPath: string): Promise<void> {
  const target = path.join(root, relPath);
  if (existsSync(target)) {
    ui.info(`Bridge ${relPath} already exists — skipped`);
    return;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, BRIDGE_BODY, "utf8");
  ui.success(`Created bridge ${relPath}`);
}

