import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { Command } from "commander";
import {
  AUTOPILOT_DEFAULTS,
  buildCodeMap,
  findProjectRoot,
  resolveHaivePaths,
  saveCodeMap,
  saveConfig,
} from "@hiveai/core";
import { ui } from "../utils/ui.js";
import { setupAgentMode } from "./agent.js";
import { applyAutopilotRepairs } from "../utils/autopilot.js";
import { generateBootstrapContext } from "./init-bootstrap.js";
import {
  autoDetectStacks,
  isValidStack,
  seedStackPack,
  SUPPORTED_STACKS,
} from "./init-stack-packs.js";

const PROJECT_CONTEXT_TEMPLATE = `# Project context

> Generated by \`haive init\`. Run \`haive init --bootstrap\` to auto-fill from your codebase,
> or invoke the MCP prompt \`bootstrap_project\` in your AI client for a richer AI-generated version.
> **AI agents**: use the **haive** MCP (\`get_briefing\` / \`mem_relevant_to\`) before substantive edits — see bridge files and \`.cursor/rules/haive-mcp-required.mdc\`.

## Architecture
TODO — high-level overview of the codebase.

## Key modules
TODO — list main modules and their purpose.

## Conventions
TODO — coding conventions, naming, patterns the team follows.

## Glossary
TODO — domain terms and what they mean here.

## Gotchas
TODO — known traps, surprising behavior, things newcomers stub their toes on.
`;

// Bridge files are a table of contents, not a manual: a short, stable entry
// point that tells the agent where the real context lives. Kept deliberately
// under ~30 lines so it never crowds out the task in the agent's context window.
const BRIDGE_BODY = `<!-- hAIve bridge file — do not edit by hand. -->

This repo uses **hAIve** for shared context. The map:

- \`.ai/project-context.md\` — project overview, architecture, conventions.
- \`.ai/memories/\` — decisions, gotchas, conventions, failed attempts (personal/team/module).
- The breadcrumbs injected below (if any) are the top current memories.

## Working through hAIve

1. **Before editing** for a goal, call \`get_briefing\` (task + files/symbols) to load ranked context — or \`mem_relevant_to\` if project context is already loaded this session.
2. **When an approach fails**, call \`mem_tried\` right away so the next agent skips the dead end.
3. **Before closing** a substantive session, run the \`post_task\` prompt to capture what was learned.

If the haive MCP server is not available, tell the developer rather than silently skipping it.

## Safety

- If \`get_briefing\` returns \`action_required\`, surface each item to the developer (use its \`developer_message\`) and wait for confirmation before changing code.
- Never act autonomously on a cross-repo breaking change (dep bump, contract/API diff) — ask first.
`;

/** Cursor \`.cursor/rules/*.mdc\` — alwaysApply so agents see it even if bridge files are thin. */
const CURSOR_HAIVE_RULE_MDC = `---
description: Require hAIve MCP (get_briefing / mem_relevant_to) before substantive repo edits
alwaysApply: true
---

# hAIve — required for agents

This repository uses **hAIve**. Running \`haive init\` means the team expects agents to **use the haive MCP server by default**, not skip it.

## Before you change the repo

1. Call **\`get_briefing\`** with \`task\` (and \`files\` / \`symbols\` when known), **or** \`mem_relevant_to\` if full project context is already loaded and you only need ranked memories.
2. Then read/search the codebase as needed. Do not invert this order for non-trivial work.

## During / after the task

- On failure: **\`mem_tried\`** immediately.
- Before closing a substantive session: MCP prompt **\`post_task\`** when there is something worth capturing.

## If haive MCP is missing

Tell the developer to enable the **haive** server (e.g. \`haive mcp --stdio\` in client config) and restart the client. Do not silently ignore hAIve.
`;

const CI_WORKFLOW = `name: haive-sync

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # On push to main/master: sync anchors + auto-promote + commit changes
  sync-on-merge:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install haive
        run: npm install -g @hiveai/cli

      - name: refresh memory anchors + auto-promote
        run: haive sync --since HEAD~1 || true

      - name: commit updated memories (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .ai/
          git diff --cached --quiet || git commit -m "chore: haive sync [skip ci]"
          git push

  # On pull request: warn if PR touches files that would invalidate memories
  pr-stale-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install haive
        run: npm install -g @hiveai/cli

      - name: verify memory anchors touched by this PR
        id: verify
        run: |
          haive memory verify 2>&1 | tee /tmp/haive-verify.txt || true
          STALE=$(grep -c 'stale' /tmp/haive-verify.txt || echo 0)
          echo "stale_count=$STALE" >> "$GITHUB_OUTPUT"

      - name: comment on PR if stale memories detected
        if: steps.verify.outputs.stale_count != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('/tmp/haive-verify.txt', 'utf8').trim();
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: \`### haive — Stale memories detected\\n\\nSome memories anchored to code modified in this PR may be outdated:\\n\\n\\\`\\\`\\\`\\n\${report}\\n\\\`\\\`\\\`\\n\\nRun \\\`haive memory verify --update\\\` locally to refresh them before merging.\`
            });

  # ── hAIve PR Memory Check ─────────────────────────────────────────────────
  # Posts a comment on every PR surfacing memories relevant to the changed files.
  # Reviewers and AI agents see gotchas, conventions, and action_required items
  # before they start coding.
  pr-memory-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: Doucs91/hAIve/packages/github-action@main
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          # post-if-empty: 'true'   # uncomment to always post (even when no memories found)
          # max-memories: '5'       # limit memories per file in the comment

  # On push to main: push shared memories to the hub (if hubPath is configured)
  # Uncomment and configure hubPath in .ai/haive.config.json to enable.
  # hub-push:
  #   if: github.event_name == 'push'
  #   needs: sync-on-merge
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: install haive
  #       run: npm install -g @hiveai/cli
  #     - name: push shared memories to hub
  #       run: haive hub push --commit
  #       # Requires hubPath in .ai/haive.config.json pointing to a cloned hub repo.
`;

export function registerInit(program: Command): void {
  program
    .command("init")
    .description(
      "Initialize a hAIve project — autopilot mode ON by default (zero human intervention).\n" +
      "  Auto-bootstraps project-context.md from local files and seeds detected stack packs.\n" +
      "  Add --manual to control memory approval and session recaps yourself.\n" +
      "  Add --no-bootstrap and --stack none to disable the auto-features.",
    )
    .option("-d, --dir <dir>", "project root", process.cwd())
    .option("--no-bridges", "do not generate CLAUDE.md / .cursorrules / copilot-instructions.md / .cursor/rules/haive-mcp-required.mdc")
    .option("--with-ci", "write a GitHub Actions workflow (.github/workflows/haive-sync.yml) — included automatically in autopilot mode")
    .option(
      "--manual",
      "opt out of autopilot: memories require manual approval, no auto-session recap, no auto-context",
    )
    .option(
      "--bootstrap",
      "auto-generate .ai/project-context.md from package.json, README, and directory structure (ON by default in autopilot)",
    )
    .option(
      "--no-bootstrap",
      "skip the project-context auto-generation (only the default template is written)",
    )
    .option(
      "--stack <stacks>",
      `pre-seed validated memory packs for the given stacks (comma-separated).\n` +
      `  Supported: ${SUPPORTED_STACKS.join(", ")}.\n` +
      `  Defaults to 'auto' in autopilot mode (detects from package.json). Pass 'none' to disable.`,
    )
    .option(
      "--no-mcp-setup",
      "skip auto-configuring haive MCP (haive mcp --stdio) in Cursor / VS Code / Claude Code",
    )
    .option(
      "-y, --yes",
      "approve user-level AI client configuration prompts during agent setup",
      false,
    )
    .action(async (opts: {
      dir: string;
      bridges: boolean;
      withCi?: boolean;
      manual?: boolean;
      bootstrap?: boolean;
      stack?: string;
      mcpSetup: boolean;
      yes?: boolean;
    }) => {
      const root = path.resolve(opts.dir);
      const paths = resolveHaivePaths(root);
      const autopilot = opts.manual !== true; // autopilot is ON by default

      // In autopilot mode, default-on the value-from-day-zero auto-features
      // unless the user explicitly opted out. opts.bootstrap is `false` only
      // when the user passed --no-bootstrap; it's `undefined` when neither flag
      // was given, which we resolve to autopilot's default.
      const wantBootstrap = opts.bootstrap === undefined ? autopilot : opts.bootstrap;
      const wantStack =
        opts.stack === undefined
          ? autopilot ? "auto" : undefined
          : opts.stack === "none" ? undefined : opts.stack;

      if (existsSync(paths.haiveDir)) {
        ui.warn(`.ai/ already exists at ${paths.haiveDir} — leaving existing files in place.`);
      }

      await mkdir(paths.personalDir, { recursive: true });
      await mkdir(paths.teamDir, { recursive: true });
      await mkdir(paths.moduleDir, { recursive: true });
      await mkdir(paths.modulesContextDir, { recursive: true });
      await ensureAiRuntimeLayout(paths.runtimeDir);
      await ensureAiCacheLayout(path.join(paths.haiveDir, ".cache"));

      // ── project-context.md ───────────────────────────────────────────────
      if (!existsSync(paths.projectContext)) {
        if (wantBootstrap) {
          ui.info("Bootstrapping project context from local files…");
          try {
            const context = await generateBootstrapContext(root);
            await writeFile(paths.projectContext, context, "utf8");
            ui.success("Created .ai/project-context.md (auto-bootstrapped from local files)");
          } catch (err) {
            ui.warn(`Bootstrap failed (${String(err)}) — writing default template instead`);
            await writeFile(paths.projectContext, PROJECT_CONTEXT_TEMPLATE, "utf8");
          }
        } else {
          await writeFile(paths.projectContext, PROJECT_CONTEXT_TEMPLATE, "utf8");
          ui.success(`Created ${path.relative(root, paths.projectContext)}`);
        }
      }

      // Write config (autopilot or default)
      const configExists = existsSync(
        path.join(paths.haiveDir, "haive.config.json"),
      );
      if (!configExists) {
        await saveConfig(paths, autopilot ? AUTOPILOT_DEFAULTS : { autopilot: false });
        ui.success(
          `Created .ai/haive.config.json (mode: ${autopilot ? "autopilot" : "standard"})`,
        );
      }

      if (opts.bridges) {
        await writeBridge(root, "CLAUDE.md");
        await writeBridge(root, ".cursorrules");
        await writeBridge(root, path.join(".github", "copilot-instructions.md"));
        await writeCursorHaiveRule(root);
      }

      // ── Stack memory packs ───────────────────────────────────────────────
      const stacksToSeed = await resolveStacksToSeed(root, wantStack);
      if (stacksToSeed.length > 0) {
        let totalSeeded = 0;
        for (const stack of stacksToSeed) {
          const count = await seedStackPack(paths, stack);
          if (count > 0) {
            ui.success(`Seeded ${count} memories for stack: ${stack}`);
            totalSeeded += count;
          } else {
            ui.info(`Stack pack '${stack}': all memories already exist — skipped`);
          }
        }
        if (totalSeeded > 0) {
          ui.success(
            `${totalSeeded} starter memories seeded (generic stack guidance, kept at background priority)`,
          );
          ui.info(
            "Anchor them to real files or replace them with repo-specific notes to make them high-signal.",
          );
        }
      }

      // autopilot: CI + enforcement hooks + code-map included automatically
      const wantCi = opts.withCi || autopilot;
      if (wantCi) {
        const ciPath = path.join(root, ".github", "workflows", "haive-sync.yml");
        if (existsSync(ciPath)) {
          ui.info("CI workflow already exists — skipped");
        } else {
          await mkdir(path.dirname(ciPath), { recursive: true });
          await writeFile(ciPath, CI_WORKFLOW, "utf8");
          ui.success(`Created ${path.relative(root, ciPath)}`);
        }
      }

      if (autopilot) {
        // Install agent-agnostic enforcement gates (MCP policy config, git hooks,
        // CI workflow, and supported client hooks such as Claude Code).
        const haiveBin = process.argv[1]!;
        const enforcementResult = spawnSync(
          process.execPath,
          [haiveBin, "enforce", "install", "--dir", root],
          { encoding: "utf8" },
        );
        if (enforcementResult.status === 0) {
          ui.success("hAIve enforcement installed (MCP, git, CI, client hooks where available)");
        } else {
          ui.warn("hAIve enforcement not fully installed — run `haive enforce install` manually");
        }

        // Build initial code-map
        try {
          ui.info("Building code-map…");
          const map = await buildCodeMap(root, { includeUntracked: true });
          await saveCodeMap(paths, map);
          ui.success(`Code-map built (${Object.keys(map.files).length} files)`);
        } catch {
          ui.warn("Code-map build failed — run `haive index code` manually");
        }

        const repairs = await applyAutopilotRepairs(root, paths, {
          applyContext: true,
          applyCorpus: true,
          applyCodeMap: false,
          applyCodeSearch: true,
        });
        for (const repair of repairs) {
          ui.info(repair.message);
        }
      }

      // ── Auto-configure MCP in AI clients ────────────────────────────────
      if (opts.mcpSetup !== false) {
        const agentSetup = await setupAgentMode(root, {
          yes: opts.yes === true,
          global: true,
          interactive: process.stdin.isTTY,
        });
        for (const r of agentSetup.project_results) {
          if (r.status === "configured" && r.path) ui.success(`haive MCP project config written (${path.relative(root, r.path)})`);
          else if (r.status === "error") ui.warn(`${r.client}: ${r.error}`);
        }
        for (const r of agentSetup.global_results) {
          if (r.status === "configured") ui.success(`haive MCP configured in ${r.client} user-level config${r.path ? ` (${r.path})` : ""}`);
          else if (r.status === "already_configured") ui.info(`haive MCP already present in ${r.client} user-level config — left unchanged (this project's config was written above)`);
        }
        if (agentSetup.global_skipped_reason) ui.warn(agentSetup.global_skipped_reason);
        ui.info(`Recommended agent mode: ${agentSetup.detection.recommended_mode}`);
        ui.info(agentSetup.detection.recommended_command);
        await ensureGitignoreEntries(root, [
          ".cursor/mcp.json",
          ".vscode/mcp.json",
          ".mcp.json",
        ]);
        ui.info(ui.dim("  → Restart your AI client for MCP changes to take effect."));
      }

      await ensureGitignoreEntries(root, [
        ".ai/.cache/*",
        "!.ai/.cache/.gitignore",
        ".ai/.runtime/*",
        "!.ai/.runtime/.gitignore",
        "!.ai/.runtime/README.md",
      ]);

      ui.success(`hAIve initialized at ${root}${autopilot ? " (autopilot mode)" : ""}`);
      console.log();

      if (autopilot) {
        console.log(ui.bold("Autopilot mode is ON — hAIve runs itself:"));
        console.log(ui.dim("  ✓ Memories go directly to validated (no approval needed)"));
        console.log(ui.dim("  ✓ Proposed memories auto-approve after 72h without rejection"));
        console.log(ui.dim("  ✓ Session recap saved automatically when the AI session closes"));
        console.log(ui.dim("  ✓ Code-map refreshes automatically after every pull"));
        console.log(ui.dim("  ✓ Agent-agnostic enforcement gates installed (MCP, git, CI, wrapper-ready)"));
        console.log(ui.dim("  ✓ CI workflows created (sync + enforcement)"));
        if (stacksToSeed.length > 0) {
          console.log(ui.dim(`  ✓ Stack memory packs pre-seeded (${stacksToSeed.join(", ")})`));
        }
        console.log();

        if (!wantBootstrap) {
          console.log(ui.bold("One remaining step (optional but recommended):"));
          console.log("  " + ui.bold("haive init --bootstrap") + ui.dim("  ← fill project-context.md without AI"));
          console.log("  " + ui.dim("Or in your AI client: invoke the MCP prompt ") + ui.bold("bootstrap_project"));
        } else {
          console.log(ui.bold("Project context bootstrapped from local files."));
          console.log(ui.dim("  Review .ai/project-context.md and fill in the TODO sections."));
          console.log(ui.dim("  Or invoke the MCP prompt `bootstrap_project` for a richer AI-generated version."));
        }
        console.log();
        console.log(ui.dim("  Seed more memories instantly:"));
        console.log(ui.dim("    haive memory import-changelog   — from CHANGELOG.md"));
        console.log(ui.dim("    haive memory import README.md   — from README / docs"));
      } else {
        console.log(ui.bold("Next steps:"));
        if (!wantBootstrap) {
          console.log(ui.dim("  1. Fill project context (pick one):"));
          console.log("     " + ui.bold("haive init --bootstrap") + ui.dim("  ← instant, no AI needed"));
          console.log("     or invoke the MCP prompt " + ui.bold("bootstrap_project") + ui.dim(" in your AI client"));
        } else {
          console.log(ui.dim("  1. Review .ai/project-context.md and fill in the TODO sections."));
        }
        console.log();
        console.log(ui.dim("  2. Start every AI session with:"));
        console.log("     " + ui.bold("get_briefing({ task: '…what you are about to do…' })"));
        console.log();
        console.log(ui.dim("  Tip: run `haive init` (without --manual) for zero-friction autopilot mode."));
      }
    });
}

async function resolveStacksToSeed(
  root: string,
  stackOpt: string | undefined,
): Promise<ReturnType<typeof autoDetectStacks>> {
  if (!stackOpt) return [];
  if (stackOpt === "auto") {
    // Auto-detect from package.json
    const pkgPath = path.join(root, "package.json");
    if (!existsSync(pkgPath)) return [];
    try {
      const pkg = JSON.parse(await readFile(pkgPath, "utf8")) as {
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
      };
      const allDeps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
      return autoDetectStacks(allDeps);
    } catch {
      return [];
    }
  }
  // Comma-separated stack names
  return stackOpt
    .split(",")
    .map((s) => s.trim().toLowerCase())
    .filter(isValidStack);
}

async function writeCursorHaiveRule(root: string): Promise<void> {
  const relPath = ".cursor/rules/haive-mcp-required.mdc";
  const target = path.join(root, relPath);
  if (existsSync(target)) {
    ui.info(`Cursor rule ${relPath} already exists — skipped`);
    return;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, CURSOR_HAIVE_RULE_MDC, "utf8");
  ui.success(`Created Cursor rule ${relPath}`);
}

async function writeBridge(root: string, relPath: string): Promise<void> {
  const target = path.join(root, relPath);
  if (existsSync(target)) {
    ui.info(`Bridge ${relPath} already exists — skipped`);
    return;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, BRIDGE_BODY, "utf8");
  ui.success(`Created bridge ${relPath}`);
}

const RUNTIME_README_BODY = `# .ai/.runtime — disposable local layer

Not team truth. Use for machine-local session notes or tooling scratch files.
Official memories belong in .ai/memories/ (versioned in Git).
Only .gitignore and this README are meant to commit; everything else stays untracked.

Session continuity (local): agents may append \`session-journal.ndjson\` via MCP \`runtime_journal_append\` or \`haive runtime journal append\`.
`;

const RUNTIME_GITIGNORE_BODY = `*
!.gitignore
!README.md
`;

async function ensureAiRuntimeLayout(runtimeDir: string): Promise<void> {
  await mkdir(runtimeDir, { recursive: true });
  const gi = path.join(runtimeDir, ".gitignore");
  if (!existsSync(gi)) {
    await writeFile(gi, RUNTIME_GITIGNORE_BODY, "utf8");
  }
  const readme = path.join(runtimeDir, "README.md");
  if (!existsSync(readme)) {
    await writeFile(readme, RUNTIME_README_BODY, "utf8");
  }
}

async function ensureAiCacheLayout(cacheDir: string): Promise<void> {
  await mkdir(cacheDir, { recursive: true });
  const gi = path.join(cacheDir, ".gitignore");
  if (!existsSync(gi)) {
    await writeFile(gi, "*\n!.gitignore\n", "utf8");
  }
}

/**
 * Append gitignore entries if they aren't already present.
 * Creates .gitignore if it doesn't exist.
 * Silently no-ops on any filesystem error (non-blocking).
 */
async function ensureGitignoreEntries(root: string, patterns: string[]): Promise<void> {
  try {
    const gitignorePath = path.join(root, ".gitignore");
    let existing = "";
    if (existsSync(gitignorePath)) {
      existing = await readFile(gitignorePath, "utf8");
    }
    const lines = existing.split("\n");
    const missing = patterns.filter((p) => !lines.some((l) => l.trim() === p));
    if (missing.length === 0) return;
    const toAppend = (existing.endsWith("\n") || existing === "" ? "" : "\n") +
      "# hAIve project-level MCP configs (machine-specific absolute paths)\n" +
      missing.join("\n") + "\n";
    await writeFile(gitignorePath, existing + toAppend, "utf8");
  } catch {
    // non-fatal
  }
}
