import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { resolveHaivePaths } from "@hiveai/core";
import type { HaiveContext } from "../src/context.js";
import { getBriefing } from "../src/tools/get-briefing.js";

const baseInput = {
  max_tokens: 4000, max_memories: 8,
  include_project_context: true, include_module_contexts: false,
  semantic: false, include_stale: false, track: false,
  format: "full" as const, symbols: [] as string[], min_semantic_score: 0,
};

async function writeMemory(dir: string, id: string, body: string, anchorPath: string): Promise<void> {
  const fm = [
    "---", `id: ${id}`, "scope: team", "type: convention", "status: validated",
    `created_at: ${new Date().toISOString()}`,
    "anchor:", `  paths: ["${anchorPath}"]`, "  symbols: []", "tags: []", "---",
  ].join("\n");
  await writeFile(path.join(dir, `${id}.md`), `${fm}\n${body}\n`, "utf8");
}

describe("adaptive briefing", () => {
  let workDir: string;
  let ctx: HaiveContext;

  beforeEach(async () => {
    workDir = await mkdtemp(path.join(tmpdir(), "haive-adaptive-"));
    const paths = resolveHaivePaths(workDir);
    await mkdir(paths.teamDir, { recursive: true });
    await mkdir(paths.personalDir, { recursive: true });
    ctx = { paths };
  });
  afterEach(async () => { await rm(workDir, { recursive: true, force: true }); });

  it("marks briefing_value=low and trims auto context when only generic knowledge matches", async () => {
    // A still-template project context is exactly the inferable noise the adaptive briefing trims.
    await writeFile(ctx.paths.projectContext, "# Project context\n\nGenerated by `haive init`. TODO.\n", "utf8");
    await writeMemory(
      ctx.paths.teamDir!, "2024-01-01-convention-generic",
      "# Generic\n\nAlways validate input and handle errors. Write tests and use meaningful names.",
      "src/svc.ts",
    );
    const b = await getBriefing({ ...baseInput, task: "edit the service", files: ["src/svc.ts"] }, ctx);
    expect(b.briefing_value).toBe("low");
    // auto-generated/template context is trimmed to a near-zero-cost note
    expect(b.project_context?.content ?? "").toMatch(/adaptive briefing/i);
  });

  it("marks briefing_value=high and keeps context when an unguessable team policy matches", async () => {
    await writeMemory(
      ctx.paths.teamDir!, "2024-01-01-convention-publicid",
      "# Public ids\n\nPublic ids are the internal id plus an offset of 100000, prefixed with 'AC-'. Example: 7 -> 'AC-100007'.",
      "src/ids.ts",
    );
    const b = await getBriefing({ ...baseInput, task: "implement toPublicId", files: ["src/ids.ts"] }, ctx);
    expect(b.briefing_value).toBe("high");
    expect(b.project_context?.content ?? "").not.toMatch(/adaptive briefing/i);
  });
});
