import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { appendPreventionEvent, loadUsageIndex, recordApplied, resolveHaivePaths, saveUsageIndex } from "@hivelore/core";
import type { HaiveContext } from "../src/context.js";
import { getBriefing } from "../src/tools/get-briefing.js";

const baseInput = {
  max_tokens: 4000, max_memories: 8,
  include_project_context: true, include_module_contexts: false,
  semantic: false, include_stale: false, track: false,
  format: "full" as const, symbols: [] as string[], min_semantic_score: 0,
};

async function writeMemory(dir: string, id: string, body: string, anchorPath: string, type = "convention"): Promise<void> {
  const fm = [
    "---", `id: ${id}`, "scope: team", `type: ${type}`, "status: validated",
    `created_at: ${new Date().toISOString()}`,
    "anchor:", `  paths: ["${anchorPath}"]`, "  symbols: []", "tags: []", "---",
  ].join("\n");
  await writeFile(path.join(dir, `${id}.md`), `${fm}\n${body}\n`, "utf8");
}

async function writeSkill(
  dir: string,
  id: string,
  body: string,
  activation: { keywords?: string[]; globs?: string[]; always?: boolean },
  anchorPath = "",
): Promise<void> {
  const lines = [
    "---", `id: ${id}`, "scope: team", "type: skill", "status: validated",
    `created_at: ${new Date().toISOString()}`,
    "anchor:", `  paths: [${anchorPath ? `"${anchorPath}"` : ""}]`, "  symbols: []", "tags: []",
    "activation:",
    `  keywords: [${(activation.keywords ?? []).map((k) => `"${k}"`).join(", ")}]`,
    `  globs: [${(activation.globs ?? []).map((g) => `"${g}"`).join(", ")}]`,
    `  always: ${activation.always ?? false}`,
    "---",
  ].join("\n");
  await writeFile(path.join(dir, `${id}.md`), `${lines}\n${body}\n`, "utf8");
}

describe("adaptive briefing", () => {
  let workDir: string;
  let ctx: HaiveContext;

  beforeEach(async () => {
    workDir = await mkdtemp(path.join(tmpdir(), "haive-adaptive-"));
    const paths = resolveHaivePaths(workDir);
    await mkdir(paths.teamDir, { recursive: true });
    await mkdir(paths.personalDir, { recursive: true });
    ctx = { paths };
  });
  afterEach(async () => { await rm(workDir, { recursive: true, force: true }); });

  it("marks briefing_value=low and trims auto context when only generic knowledge matches", async () => {
    // A still-template project context is exactly the inferable noise the adaptive briefing trims.
    await writeFile(ctx.paths.projectContext, "# Project context\n\nGenerated by `hivelore init`. TODO.\n", "utf8");
    await writeMemory(
      ctx.paths.teamDir!, "2024-01-01-convention-generic",
      "# Generic\n\nAlways validate input and handle errors. Write tests and use meaningful names.",
      "src/svc.ts",
    );
    const b = await getBriefing({ ...baseInput, task: "edit the service", files: ["src/svc.ts"] }, ctx);
    expect(b.briefing_value).toBe("low");
    // auto-generated/template context is trimmed to a near-zero-cost note
    expect(b.project_context?.content ?? "").toMatch(/adaptive briefing/i);
  });

  it("marks briefing_value=high and keeps context when an unguessable team policy matches", async () => {
    await writeMemory(
      ctx.paths.teamDir!, "2024-01-01-convention-publicid",
      "# Public ids\n\nPublic ids are the internal id plus an offset of 100000, prefixed with 'AC-'. Example: 7 -> 'AC-100007'.",
      "src/ids.ts",
    );
    const b = await getBriefing({ ...baseInput, task: "implement toPublicId", files: ["src/ids.ts"] }, ctx);
    expect(b.briefing_value).toBe("high");
    expect(b.project_context?.content ?? "").not.toMatch(/adaptive briefing/i);
  });

  it("surfaces the measured prevention proof line in hints when recent catches exist", async () => {
    await writeMemory(
      ctx.paths.teamDir!, "2024-01-01-gotcha-legacyfield",
      "# Avoid legacyField\n\nNever reintroduce legacyField; use currentField.",
      "src/svc.ts", "gotcha",
    );
    // Two recent catches → briefingProofLine should report them in-context.
    const recent = new Date().toISOString();
    await appendPreventionEvent(ctx.paths, { at: recent, id: "2024-01-01-gotcha-legacyfield", source: "sensor" });
    await appendPreventionEvent(ctx.paths, { at: recent, id: "2024-01-01-gotcha-legacyfield", source: "anti-pattern" });

    const b = await getBriefing({ ...baseInput, task: "edit the service", files: ["src/svc.ts"] }, ctx);
    expect((b.hints ?? []).some((h) => /prevented 2 repeated mistakes/i.test(h))).toBe(true);
  });

  it("does not show a proof line when there are no recent prevention events", async () => {
    await writeMemory(
      ctx.paths.teamDir!, "2024-01-01-convention-pure",
      "# Pure handlers\n\nKeep request handlers pure and side-effect free.",
      "src/svc.ts",
    );
    const b = await getBriefing({ ...baseInput, task: "edit the service", files: ["src/svc.ts"] }, ctx);
    expect((b.hints ?? []).some((h) => /prevented .* repeated mistake/i.test(h))).toBe(false);
  });

  it("ranks an applied memory above an equally-relevant never-applied one and surfaces impact_tier", async () => {
    // Two memories anchored to the same file → identical relevance/confidence; impact is the only differentiator.
    await writeMemory(ctx.paths.teamDir!, "2024-01-01-convention-applied", "# Applied rule\n\nKeep handlers pure.", "src/svc.ts");
    await writeMemory(ctx.paths.teamDir!, "2024-01-01-convention-unused", "# Unused rule\n\nKeep handlers pure.", "src/svc.ts");

    const idx = await loadUsageIndex(ctx.paths);
    for (let i = 0; i < 4; i++) recordApplied(idx, "2024-01-01-convention-applied");
    await saveUsageIndex(ctx.paths, idx);

    const b = await getBriefing({ ...baseInput, task: "edit the service handler", files: ["src/svc.ts"] }, ctx);
    expect(b.memories[0]?.id).toBe("2024-01-01-convention-applied");
    expect(b.memories[0]?.impact_tier).toBe("high");
    const unused = b.memories.find((m) => m.id === "2024-01-01-convention-unused");
    expect(unused?.impact_score ?? 0).toBeLessThan(b.memories[0]!.impact_score ?? 0);
  });

  it("progressive disclosure: suppresses a lexically-matching skill whose activation does not fire", async () => {
    // Both skill bodies share the task's tokens, so both WOULD surface via literal match.
    // Only the activation block should decide which is disclosed.
    await writeSkill(ctx.paths.teamDir!, "2024-01-01-skill-stripe", "# Stripe retries\n\nstripe payment retries playbook.", { keywords: ["stripe"] });
    await writeSkill(ctx.paths.teamDir!, "2024-01-01-skill-graphql", "# GraphQL note\n\nstripe payment retries via the graphql gateway.", { keywords: ["graphql"] });

    const b = await getBriefing({ ...baseInput, task: "set up stripe payment retries", files: [] }, ctx);
    const ids = b.memories.map((m) => m.id);
    expect(ids).toContain("2024-01-01-skill-stripe"); // keyword "stripe" matches → disclosed
    expect(ids).not.toContain("2024-01-01-skill-graphql"); // would match lexically, but activation "graphql" does not fire → suppressed
  });

  it("an activated skill is ranked above an equally-anchored non-skill memory", async () => {
    await writeMemory(ctx.paths.teamDir!, "2024-01-01-convention-auth", "# Auth rule\n\nUse the auth guard.", "src/auth.ts");
    await writeSkill(ctx.paths.teamDir!, "2024-01-01-skill-auth", "# Auth playbook\n\nSteps to add an endpoint.", { globs: ["src/auth.ts"] }, "src/auth.ts");

    const b = await getBriefing({ ...baseInput, task: "add an endpoint", files: ["src/auth.ts"] }, ctx);
    expect(b.memories[0]?.id).toBe("2024-01-01-skill-auth");
  });

  it("lexical rerank lifts the on-topic memory above a structurally-favored attempt", async () => {
    // The attempt gets a type bonus (+3) and would win on the old additive ranking.
    // The target matches the query's distinctive terms (graphql, dataloader) → BM25 lifts it.
    await writeMemory(ctx.paths.teamDir!, "2024-01-01-attempt-caching", "# Caching note\n\nA caching layer failed once here.", "src/a.ts", "attempt");
    await writeMemory(ctx.paths.teamDir!, "2024-01-01-convention-graphql", "# GraphQL\n\nUse a GraphQL dataloader to batch resolver caching.", "src/b.ts", "convention");

    // Both surface (share "caching"); only the target matches graphql+dataloader.
    const b = await getBriefing({ ...baseInput, task: "graphql dataloader caching", files: [] }, ctx);
    const ids = b.memories.map((m) => m.id);
    expect(ids).toContain("2024-01-01-convention-graphql");
    expect(ids.indexOf("2024-01-01-convention-graphql")).toBeLessThan(
      ids.indexOf("2024-01-01-attempt-caching") === -1 ? Infinity : ids.indexOf("2024-01-01-attempt-caching"),
    );
    expect(b.memories[0]?.id).toBe("2024-01-01-convention-graphql");
  });
});

describe("stack-pack rescue in get_briefing (shared classifier, literal path)", () => {
  let workDir: string;
  let ctx: HaiveContext;

  beforeEach(async () => {
    workDir = await mkdtemp(path.join(tmpdir(), "haive-stackrescue-"));
    const paths = resolveHaivePaths(workDir);
    await mkdir(paths.teamDir, { recursive: true });
    await mkdir(paths.personalDir, { recursive: true });
    ctx = { paths };
  });
  afterEach(async () => { await rm(workDir, { recursive: true, force: true }); });

  const stackMemory = (id: string, body: string): string => [
    "---", `id: ${id}`, "scope: team", "type: convention", "status: validated",
    `created_at: ${new Date().toISOString()}`,
    "anchor:", "  paths: []", "  symbols: []",
    "tags:", "  - stack-pack", "  - needs_anchor", "---", body, "",
  ].join("\n");

  it("an exact literal task hit lifts an anchor-less stack seed to useful; unrelated seeds stay background", async () => {
    const paths = resolveHaivePaths(workDir);
    await writeFile(
      path.join(paths.teamDir, "2026-01-01-convention-prisma-migrations-never-modify.md"),
      stackMemory("2026-01-01-convention-prisma-migrations-never-modify", "# Prisma migrations never modify\n\nNever modify an applied prisma migration."),
      "utf8",
    );
    await writeFile(
      path.join(paths.teamDir, "2026-01-01-convention-nextjs-metadata-api.md"),
      stackMemory("2026-01-01-convention-nextjs-metadata-api", "# Nextjs metadata api\n\nUse the metadata API for SEO tags."),
      "utf8",
    );

    const out = await getBriefing({ ...baseInput, task: "prisma migrations", files: [] }, ctx);
    const prisma = out.memories.find((m) => m.id.includes("prisma"));
    const nextjs = out.memories.find((m) => m.id.includes("nextjs"));
    expect(prisma?.priority).toBe("useful");
    // No task overlap: the generic seed stays smothered so it can't crowd the briefing.
    if (nextjs) expect(nextjs.priority).toBe("background");
  });
});
