import { describe, expect, it } from "vitest";
import { assessBootstrapState, renderBootstrapChecklist } from "../src/bootstrap-state.js";
import type { LoadedMemory } from "../src/loader.js";

function mem(opts: {
  status?: string;
  scope?: string;
  paths?: string[];
  sensor?: boolean;
}): LoadedMemory {
  return {
    filePath: `/x/${Math.random()}.md`,
    memory: {
      frontmatter: {
        id: "m",
        scope: opts.scope ?? "team",
        type: "gotcha",
        status: opts.status ?? "validated",
        anchor: { paths: opts.paths ?? [], symbols: [] },
        sensor: opts.sensor
          ? { kind: "regex", pattern: "x", paths: opts.paths ?? [], message: "m", severity: "warn", autogen: true, last_fired: null }
          : undefined,
      },
      body: "body",
    },
  } as unknown as LoadedMemory;
}

const FILLED_CONTEXT =
  "# Project context\n\n## Architecture\n" +
  "A real description of the system that is clearly not the template and is long enough to pass the floor. ".repeat(4);

// Two components, each with >= 3 production files.
const TWO_COMPONENT_FILES = [
  "packages/api/a.ts", "packages/api/b.ts", "packages/api/c.ts",
  "packages/web/x.ts", "packages/web/y.ts", "packages/web/z.ts",
];

describe("assessBootstrapState", () => {
  it("is cold on a fresh repo: template context + no memories", () => {
    const a = assessBootstrapState({
      projectContextRaw: "Generated by `hivelore init`",
      memories: [],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: [],
    });
    expect(a.state).toBe("cold");
    expect(a.gaps.map((g) => g.kind)).toContain("project-context");
    expect(a.gaps.map((g) => g.kind)).toContain("sensor-coverage");
  });

  it("is partial once context is filled but areas lack memories/sensors", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [mem({ paths: ["packages/api/a.ts"], sensor: true })], // covers api only
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    expect(a.state).toBe("partial");
    // web still uncovered for both memory and sensor
    const sensorGap = a.gaps.find((g) => g.kind === "sensor-coverage");
    expect(sensorGap?.items).toEqual(["packages/web"]);
  });

  it("is ready when every component has a module context, an anchored memory, and a sensor", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        mem({ paths: ["packages/api/a.ts"], sensor: true }),
        mem({ paths: ["packages/web/x.ts"], sensor: true }),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    expect(a.state).toBe("ready");
    expect(a.gaps).toHaveLength(0);
    expect(renderBootstrapChecklist(a)).toMatch(/ready/i);
  });

  it("flags a missing module context for a multi-component repo", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        mem({ paths: ["packages/api/a.ts"], sensor: true }),
        mem({ paths: ["packages/web/x.ts"], sensor: true }),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api"], // web module context missing
    });
    const moduleGap = a.gaps.find((g) => g.kind === "module-context");
    expect(moduleGap?.items).toEqual(["packages/web"]);
    expect(a.state).not.toBe("ready");
  });

  it("requires no module context for a single-component repo", () => {
    const files = ["src/a.ts", "src/b.ts", "src/c.ts"];
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [mem({ paths: ["src/a.ts"], sensor: true })],
      codeFiles: files,
      existingModules: [],
    });
    expect(a.gaps.find((g) => g.kind === "module-context")).toBeUndefined();
    expect(a.state).toBe("ready");
  });

  it("does not demand sensor coverage when there are no main code areas", () => {
    // A tiny/docs repo: a single file is below the component floor → no areas to guard.
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [],
      codeFiles: ["README-ish/only-one.ts"],
      existingModules: [],
    });
    expect(a.metrics.mainAreas).toBe(0);
    expect(a.gaps.find((g) => g.kind === "sensor-coverage")).toBeUndefined();
  });

  it("does not treat a filled context as template just because prose mentions auto-generated", () => {
    // Regression: the over-broad /Auto-generated by `hivelore init/i check flagged a real, filled context
    // whose glossary said "Bridge files are auto-generated by `hivelore init`". The marker only counts
    // alongside the unfilled `TODO —` placeholders.
    const filled =
      FILLED_CONTEXT +
      "\n\n## Glossary\n- Bridge file: CLAUDE.md etc. auto-generated by `hivelore init`.\n";
    const a = assessBootstrapState({
      projectContextRaw: filled,
      memories: [
        mem({ paths: ["packages/api/a.ts"], sensor: true }),
        mem({ paths: ["packages/web/x.ts"], sensor: true }),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    expect(a.metrics.projectContextFilled).toBe(true);
    expect(a.gaps.find((g) => g.kind === "project-context")).toBeUndefined();
    expect(a.state).toBe("ready");
  });

  it("counts a declared container component (packages/x) even below the file floor", () => {
    // A workspace package with only 1-2 files is still a real component and must not be hidden.
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [],
      codeFiles: ["packages/utils/index.ts"], // single file under a container dir
      existingModules: [],
    });
    expect(a.metrics.components).toContain("packages/utils");
    expect(a.metrics.mainAreas).toBe(1);
  });

  it("ignores test files when computing components", () => {
    const files = [
      "src/a.ts", "src/b.ts",
      "src/a.test.ts", "src/b.spec.ts", "src/__tests__/c.ts",
    ];
    // Bare dir (not a declared container): only 2 production files → below the 3-file floor → not a main area.
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [],
      codeFiles: files,
      existingModules: [],
    });
    expect(a.metrics.mainAreas).toBe(0);
  });
});

describe("assessBootstrapState — glob-scoped BLOCK sensors credit the areas they guard", () => {
  const stackMem = (severity: "warn" | "block", scopes: string[]): LoadedMemory =>
    ({
      filePath: `/x/${Math.random()}.md`,
      memory: {
        frontmatter: {
          id: "stack",
          scope: "team",
          type: "gotcha",
          status: "validated",
          anchor: { paths: [], symbols: [] }, // stack packs ship anchor-less (needs_anchor)
          sensor: { kind: "regex", pattern: "x", paths: scopes, message: "m", severity, autogen: true, last_fired: null },
        },
        body: "body",
      },
    }) as unknown as LoadedMemory;

  it("a validated block sensor with a glob scope closes the sensor-coverage gap for matching areas", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        // Anchored memories cover knowledge for both areas; only web has an area sensor.
        mem({ paths: ["packages/api/a.ts"] }),
        mem({ paths: ["packages/web/x.ts"], sensor: true }),
        stackMem("block", ["**/*.ts"]),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    expect(a.gaps.find((g) => g.kind === "sensor-coverage")).toBeUndefined();
  });

  it("warn glob sensors do NOT count — they cannot block a repeat", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        mem({ paths: ["packages/api/a.ts"] }),
        mem({ paths: ["packages/web/x.ts"] }),
        stackMem("warn", ["**"]),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    const gap = a.gaps.find((g) => g.kind === "sensor-coverage");
    expect(gap?.items).toEqual(["packages/api", "packages/web"]);
  });

  it("a block sensor glob that matches nothing in an area leaves that area uncovered", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        mem({ paths: ["packages/api/a.ts"] }),
        mem({ paths: ["packages/web/x.ts"] }),
        stackMem("block", ["**/*.controller.ts"]), // no controllers in either area
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    const gap = a.gaps.find((g) => g.kind === "sensor-coverage");
    expect(gap?.items).toEqual(["packages/api", "packages/web"]);
  });
});
