import { describe, expect, it } from "vitest";
import { assessBootstrapState, renderBootstrapChecklist } from "../src/bootstrap-state.js";
import type { LoadedMemory } from "../src/loader.js";

function mem(opts: {
  status?: string;
  scope?: string;
  paths?: string[];
  sensor?: boolean;
}): LoadedMemory {
  return {
    filePath: `/x/${Math.random()}.md`,
    memory: {
      frontmatter: {
        id: "m",
        scope: opts.scope ?? "team",
        type: "gotcha",
        status: opts.status ?? "validated",
        anchor: { paths: opts.paths ?? [], symbols: [] },
        sensor: opts.sensor
          ? { kind: "regex", pattern: "x", paths: opts.paths ?? [], message: "m", severity: "warn", autogen: true, last_fired: null }
          : undefined,
      },
      body: "body",
    },
  } as unknown as LoadedMemory;
}

const FILLED_CONTEXT =
  "# Project context\n\n## Architecture\n" +
  "A real description of the system that is clearly not the template and is long enough to pass the floor. ".repeat(4);

// Two components, each with >= 3 production files.
const TWO_COMPONENT_FILES = [
  "packages/api/a.ts", "packages/api/b.ts", "packages/api/c.ts",
  "packages/web/x.ts", "packages/web/y.ts", "packages/web/z.ts",
];

describe("assessBootstrapState", () => {
  it("is cold on a fresh repo: template context + no memories", () => {
    const a = assessBootstrapState({
      projectContextRaw: "Generated by `haive init`",
      memories: [],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: [],
    });
    expect(a.state).toBe("cold");
    expect(a.gaps.map((g) => g.kind)).toContain("project-context");
    expect(a.gaps.map((g) => g.kind)).toContain("sensor-coverage");
  });

  it("is partial once context is filled but areas lack memories/sensors", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [mem({ paths: ["packages/api/a.ts"], sensor: true })], // covers api only
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    expect(a.state).toBe("partial");
    // web still uncovered for both memory and sensor
    const sensorGap = a.gaps.find((g) => g.kind === "sensor-coverage");
    expect(sensorGap?.items).toEqual(["packages/web"]);
  });

  it("is ready when every component has a module context, an anchored memory, and a sensor", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        mem({ paths: ["packages/api/a.ts"], sensor: true }),
        mem({ paths: ["packages/web/x.ts"], sensor: true }),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api", "web"],
    });
    expect(a.state).toBe("ready");
    expect(a.gaps).toHaveLength(0);
    expect(renderBootstrapChecklist(a)).toMatch(/ready/i);
  });

  it("flags a missing module context for a multi-component repo", () => {
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [
        mem({ paths: ["packages/api/a.ts"], sensor: true }),
        mem({ paths: ["packages/web/x.ts"], sensor: true }),
      ],
      codeFiles: TWO_COMPONENT_FILES,
      existingModules: ["api"], // web module context missing
    });
    const moduleGap = a.gaps.find((g) => g.kind === "module-context");
    expect(moduleGap?.items).toEqual(["packages/web"]);
    expect(a.state).not.toBe("ready");
  });

  it("requires no module context for a single-component repo", () => {
    const files = ["src/a.ts", "src/b.ts", "src/c.ts"];
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [mem({ paths: ["src/a.ts"], sensor: true })],
      codeFiles: files,
      existingModules: [],
    });
    expect(a.gaps.find((g) => g.kind === "module-context")).toBeUndefined();
    expect(a.state).toBe("ready");
  });

  it("does not demand sensor coverage when there are no main code areas", () => {
    // A tiny/docs repo: a single file is below the component floor → no areas to guard.
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [],
      codeFiles: ["README-ish/only-one.ts"],
      existingModules: [],
    });
    expect(a.metrics.mainAreas).toBe(0);
    expect(a.gaps.find((g) => g.kind === "sensor-coverage")).toBeUndefined();
  });

  it("ignores test files when computing components", () => {
    const files = [
      "packages/api/a.ts", "packages/api/b.ts",
      "packages/api/a.test.ts", "packages/api/b.spec.ts", "packages/api/__tests__/c.ts",
    ];
    // Only 2 production files in api → below the 3-file floor → not a main area.
    const a = assessBootstrapState({
      projectContextRaw: FILLED_CONTEXT,
      memories: [],
      codeFiles: files,
      existingModules: [],
    });
    expect(a.metrics.mainAreas).toBe(0);
  });
});
