import { it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, rm, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { resolveHaivePaths } from "../src/paths.js";
import { appendPreventionEvent, type PreventionEvent } from "../src/prevention.js";
import { preventionCatchId, recordReportedOutcome, loadKnowledgeOutcomes, correlateKnowledgeOutcomes } from "../src/outcomes.js";
import { readMcpRuntimeInstances } from "../src/mcp-runtime.js";
import { appendSensorEvaluations, loadSensorLedger, type SensorEvaluation } from "../src/sensor-ledger.js";
let root: string;
beforeEach(async () => { root = await mkdtemp(path.join(tmpdir(), "outcomes-")); });
afterEach(async () => { await rm(root, { recursive: true, force: true }); });
it("validates catch identity, correction order and evidence references without inflating evidence", async () => {
  const paths = resolveHaivePaths(root);
  const caught: PreventionEvent = { id: "rule", at: "2026-01-01T00:00:00Z", source: "sensor", kind: "ast", stage: "manual" };
  await appendPreventionEvent(paths, caught);
  const event = { id: "rule", kind: "verified" as const, catch_id: preventionCatchId(caught), source: "mcp" as const, reference: "test-report" };
  await expect(recordReportedOutcome(paths, event)).rejects.toThrow("correction");
  await expect(recordReportedOutcome(paths, { ...event, id: "other" })).rejects.toThrow("catch_id");
  await expect(recordReportedOutcome(paths, { ...event, kind: "corrected", reference: " " })).rejects.toThrow("reference");
  await recordReportedOutcome(paths, { ...event, kind: "corrected", reference: "commit" });
  await recordReportedOutcome(paths, event);
  const reports = await loadKnowledgeOutcomes(paths);
  expect(reports.every(r => r.evidence === "reported")).toBe(true);
  const evaluation: SensorEvaluation = { at: new Date(Date.now() + 10).toISOString(), memory_id: "rule", kind: "ast", stage: "manual", head_sha: "sha", scope_hash: "hash", outcome: "silent" };
  await appendSensorEvaluations(paths, [evaluation]);
  expect(await loadSensorLedger(paths)).toEqual([evaluation]);
  expect(correlateKnowledgeOutcomes([caught], reports, [evaluation])[0]).toMatchObject({ status: "subsequent-check-silent", subsequent_silent_check: evaluation });
  expect(correlateKnowledgeOutcomes([caught], reports, [{ ...evaluation, stage: "ci" }])[0]!.subsequent_silent_check).toBeNull();
  expect(correlateKnowledgeOutcomes([caught], [], [evaluation])[0]!.subsequent_silent_check).toBeNull();
  const next = { ...caught, at: new Date().toISOString() };
  expect(correlateKnowledgeOutcomes([caught, next], reports, [evaluation])[0]!.subsequent_silent_check).toBeNull();
});
it("a new MCP diagnostic cannot hide an old live process; dead receipts are ignored", async () => {
  const paths = resolveHaivePaths(root);
  await mkdir(path.join(paths.runtimeDir, "mcp-servers"), { recursive: true });
  await writeFile(path.join(paths.runtimeDir, "mcp-server.json"), JSON.stringify({ version: "old", pid: 100 }));
  for (const pid of [101, 102]) await writeFile(path.join(paths.runtimeDir, "mcp-servers", `${pid}.json`), JSON.stringify({ version: "new", pid }));
  expect(await readMcpRuntimeInstances(paths, pid => pid !== 102)).toEqual([{ version: "old", pid: 100 }, { version: "new", pid: 101 }]);
});
