/**
 * First-agent bootstrap state — is the repo's knowledge layer filled enough for later agents to rely on?
 *
 * The trigger for forcing a bootstrap is NOT an agent identity or a flag: it is the COLD STATE of the
 * corpus itself. The very first agent on a fresh `hivelore init` faces an empty knowledge layer; this
 * assessment turns "fill everything that must be filled" into a FINITE, repo-derived checklist so the
 * gate has a precise, reachable DONE state. Once the baseline exists the assessment returns `ready`
 * and every gate that consults it goes silent — so only the first agent ever pays the cost.
 *
 * Pure domain logic: no I/O. Callers load memories / code-map / module dirs and pass them in.
 */
import type { LoadedMemory } from "./loader.js";

/** Top-level directories that contain components in a monorepo. */
const CONTAINER_DIRS = new Set([
  "packages", "apps", "services", "libs", "modules", "components", "features",
]);

/** A code area needs at least this many production files to count as a "main area" worth its own knowledge. */
const MIN_COMPONENT_FILES = 3;

/** Minimum filled length (chars) for project-context to count as a real overview rather than a stub. */
const MIN_CONTEXT_CHARS = 200;

export type BootstrapGate = "off" | "warn" | "block";
export type BootstrapState = "cold" | "partial" | "ready";

export interface BootstrapGap {
  kind: "project-context" | "module-context" | "memory-coverage" | "sensor-coverage" | "index-code";
  /** Human/agent-readable description of what is missing. */
  detail: string;
  /** Concrete items the gap applies to (component names / areas). */
  items: string[];
  /** Exact tool/command call that closes the gap. */
  fix: string;
}

export interface BootstrapMetrics {
  projectContextFilled: boolean;
  components: string[];
  modulesCovered: number;
  modulesRequired: number;
  memoryCoveredAreas: number;
  sensorCoveredAreas: number;
  mainAreas: number;
  teamMemories: number;
  sensors: number;
}

export interface BootstrapAssessment {
  state: BootstrapState;
  /** Empty exactly when state === "ready". */
  gaps: BootstrapGap[];
  metrics: BootstrapMetrics;
}

export interface BootstrapStateInput {
  /** Raw project-context.md content ("" if absent). */
  projectContextRaw: string;
  /** All memories loaded from .ai/memories. */
  memories: LoadedMemory[];
  /** Code file paths from the code-map (raw; this module filters out non-production files). */
  codeFiles: string[];
  /** Module names present under .ai/modules/<name>/ (directory names). */
  existingModules: string[];
}

/**
 * project-context is still the auto-generated template / stub rather than real content.
 * Matches the canonical detection used in briefing.ts / get-briefing: the auto-context marker counts
 * ONLY when the unfilled `TODO —` placeholders are still present (>=2). A filled context that merely
 * mentions "auto-generated by `hivelore init`" in prose (e.g. a glossary line) is NOT a template.
 */
export function isTemplateProjectContext(raw: string): boolean {
  if (raw.includes("TODO — high-level overview")) return true;
  if (raw.includes("Generated by `hivelore init`")) return true;
  if (/Auto-generated by `hivelore init/i.test(raw) && (raw.match(/TODO —/g)?.length ?? 0) >= 2) return true;
  return false;
}

function isProductionCodeFile(file: string): boolean {
  const base = file.split("/").pop() ?? file;
  if (/\.(test|spec)\.[cm]?[jt]sx?$/.test(base)) return false;
  if (/(^|\/)(test|tests|__tests__|__mocks__|e2e|fixtures)(\/|$)/.test(file)) return false;
  if (base.endsWith(".d.ts")) return false;
  if (base.endsWith(".config.ts") || base.endsWith(".config.js") || base.endsWith(".config.mjs")) return false;
  return true;
}

/** Derive the component (main code area) a file belongs to. */
export function componentOf(file: string): string {
  const parts = file.replace(/^\/+/, "").split("/").filter(Boolean);
  if (parts.length >= 2 && CONTAINER_DIRS.has(parts[0]!)) return `${parts[0]}/${parts[1]}`;
  return parts[0] ?? "";
}

/** The module-context directory name for a component (its last path segment). */
export function moduleNameOf(component: string): string {
  const parts = component.split("/").filter(Boolean);
  return parts[parts.length - 1] ?? component;
}

function anchorMatchesComponent(anchorPath: string, component: string): boolean {
  const a = anchorPath.replace(/^\/+/, "");
  if (!a) return false;
  return (
    a === component ||
    a.startsWith(component + "/") ||
    component.startsWith(a + "/") ||
    componentOf(a) === component
  );
}

/**
 * Assess whether the repo knowledge layer is filled enough (the EXHAUSTIVE bar):
 *  1. project-context.md is filled (not the template, and substantial)
 *  2. every detected component (≥2) has a module context
 *  3. every main code area has at least one anchored memory  (knowledge coverage)
 *  4. every main code area has at least one memory carrying a sensor (guardrail coverage)
 */
export function assessBootstrapState(input: BootstrapStateInput): BootstrapAssessment {
  const projectContextFilled =
    !isTemplateProjectContext(input.projectContextRaw) &&
    input.projectContextRaw.trim().length >= MIN_CONTEXT_CHARS;

  const codeFiles = input.codeFiles.filter(isProductionCodeFile);

  // Group production files into components and keep the ones large enough to deserve their own knowledge.
  const fileCounts = new Map<string, number>();
  for (const f of codeFiles) {
    const c = componentOf(f);
    if (!c) continue;
    fileCounts.set(c, (fileCounts.get(c) ?? 0) + 1);
  }
  const components = [...fileCounts.entries()]
    // A container-based component (packages/x, apps/x — has a "/") is a DECLARED component: it counts
    // regardless of size. A bare top-level dir needs the file floor so trivial folders aren't treated
    // as a main area. (Avoids silently hiding small-but-real workspace packages from the gate.)
    .filter(([c, n]) => c.includes("/") || n >= MIN_COMPONENT_FILES)
    .map(([c]) => c)
    .sort();

  const anchoredMemories = input.memories.filter(
    (m) =>
      (m.memory.frontmatter.status === "validated" || m.memory.frontmatter.status === "proposed") &&
      m.memory.frontmatter.anchor.paths.length > 0,
  );
  const sensorMemories = anchoredMemories.filter((m) => Boolean(m.memory.frontmatter.sensor));
  const teamMemories = input.memories.filter(
    (m) => m.memory.frontmatter.scope === "team" && m.memory.frontmatter.status !== "rejected",
  ).length;

  const areaCovered = (component: string, pool: LoadedMemory[]): boolean =>
    pool.some((m) =>
      m.memory.frontmatter.anchor.paths.some((p) => anchorMatchesComponent(p, component)),
    );

  // Module-context requirement only applies to genuinely multi-component repos.
  const modulesRequired = components.length >= 2 ? components : [];
  const missingModules = modulesRequired.filter(
    (c) => !input.existingModules.includes(moduleNameOf(c)),
  );

  const memoryUncovered = components.filter((c) => !areaCovered(c, anchoredMemories));
  const sensorUncovered = components.filter((c) => !areaCovered(c, sensorMemories));

  const gaps: BootstrapGap[] = [];

  if (!projectContextFilled) {
    gaps.push({
      kind: "project-context",
      detail: "project-context.md is still the template / a stub — it must describe the stack, architecture, and conventions.",
      items: [],
      fix: "Invoke the bootstrap_repo (or bootstrap_project) MCP prompt; the agent writes it via bootstrap_project_save.",
    });
  }

  if (input.codeFiles.length === 0) {
    gaps.push({
      kind: "index-code",
      detail: "No code-map found, so Hivelore cannot verify per-area knowledge coverage.",
      items: [],
      fix: "Run `hivelore index code`, then re-run the bootstrap.",
    });
  }

  if (missingModules.length > 0) {
    gaps.push({
      kind: "module-context",
      detail: `${missingModules.length} component(s) have no module context.`,
      items: missingModules,
      fix: "For each: bootstrap_project_save with module=<name> (or write .ai/modules/<name>/context.md).",
    });
  }

  if (memoryUncovered.length > 0) {
    gaps.push({
      kind: "memory-coverage",
      detail: `${memoryUncovered.length} main code area(s) have no anchored memory — later agents would get no team knowledge there.`,
      items: memoryUncovered,
      fix: "For each: mem_save a real decision/gotcha/convention anchored to a file in that area (paths=...).",
    });
  }

  if (sensorUncovered.length > 0) {
    gaps.push({
      kind: "sensor-coverage",
      detail: `${sensorUncovered.length} main code area(s) have no guardrail (sensor) — the gate cannot block a repeat there.`,
      items: sensorUncovered,
      fix: "For each: propose_sensor on a memory in that area (pattern = faulty usage, absent = correct-usage marker); core validates before trusting it to block.",
    });
  }

  const metrics: BootstrapMetrics = {
    projectContextFilled,
    components,
    modulesCovered: modulesRequired.length - missingModules.length,
    modulesRequired: modulesRequired.length,
    memoryCoveredAreas: components.length - memoryUncovered.length,
    sensorCoveredAreas: components.length - sensorUncovered.length,
    mainAreas: components.length,
    teamMemories,
    sensors: sensorMemories.length,
  };

  // Cold = a genuinely empty knowledge layer (fresh repo). Ready = no gaps. Partial = in between.
  const cold = !projectContextFilled || teamMemories === 0;
  const state: BootstrapState = gaps.length === 0 ? "ready" : cold ? "cold" : "partial";

  return { state, gaps, metrics };
}

/** Render the assessment's gaps as a numbered checklist for an agent (action_required / gate message). */
export function renderBootstrapChecklist(assessment: BootstrapAssessment): string {
  if (assessment.gaps.length === 0) return "Bootstrap complete — the repo knowledge layer is ready.";
  const lines = assessment.gaps.map((g, i) => {
    const items = g.items.length > 0 ? ` [${g.items.join(", ")}]` : "";
    return `${i + 1}. ${g.detail}${items}\n   → ${g.fix}`;
  });
  return lines.join("\n");
}
