import type { Sensor } from "./types.js";

const CODE_TOKEN_RE = /`([^`\n]{3,80})`|["']([A-Za-z0-9_.:-]{3,80})["']|\b([A-Za-z][A-Za-z0-9_.:-]{2,79})\b/g;

const SENSOR_STOPWORDS = new Set([
  "about", "after", "again", "agent", "always", "anchor", "approach", "because",
  "before", "break", "broken", "cannot", "change", "code", "commit", "correct",
  "could", "default", "detect", "direct", "directory", "does", "error", "failed",
  "fails", "file", "files", "future", "instead", "memory", "never", "project",
  "recorded", "repo", "return", "should", "source", "string", "this",
  "tried", "true", "type", "undefined", "value", "when", "where", "which", "with",
  "without",
]);

export interface SensorSuggestionOptions {
  /** Extra paths to put on the sensor. Defaults to the memory anchor paths. */
  paths?: string[];
}

/**
 * Conservatively suggest a regex sensor from a gotcha/attempt body.
 *
 * This helper intentionally returns null more often than it guesses. Autogenerated
 * sensors start as `warn`, never `block`; humans can promote them after seeing them fire.
 */
export function suggestSensorFromMemory(
  body: string,
  anchorPaths: string[],
  options: SensorSuggestionOptions = {},
): Sensor | null {
  const paths = options.paths ?? anchorPaths;
  if (paths.length === 0) return null;

  const negativeText = body.split(/\*\*Instead,\s*use:\*\*|^##\s+Instead\b/im)[0] ?? body;
  const assignment = pickAssignmentPattern(negativeText);
  const lowercaseValue = assignment ? null : pickLowercaseValuePattern(negativeText);
  const token = assignment?.label ?? lowercaseValue?.label ?? pickDistinctiveToken(negativeText);
  if (!token) return null;

  return {
    kind: "regex",
    pattern: assignment?.pattern ?? lowercaseValue?.pattern ?? escapeRegExp(token),
    paths,
    message: sensorMessageFromBody(body, token),
    severity: "warn",
    autogen: true,
    last_fired: null,
  };
}

function pickLowercaseValuePattern(text: string): { label: string; pattern: string; score: number } | null {
  const candidates: Array<{ label: string; pattern: string; score: number }> = [];
  for (const match of text.matchAll(/\blowercase\s+([A-Za-z][A-Za-z0-9_.:-]{2,79})\s+([a-z][a-z0-9_.:-]{1,40})\b/g)) {
    const key = match[1] ?? "";
    const value = match[2] ?? "";
    if (!isDistinctiveToken(key, true) || isBoringValue(value)) continue;
    candidates.push({
      label: `${key}=${value}`,
      pattern: `${escapeRegExp(key)}\\s*[:=]\\s*["']?${escapeRegExp(value)}["']?`,
      score: key.length + value.length + 35,
    });
  }
  return candidates.sort((a, b) => b.score - a.score)[0] ?? null;
}

function pickAssignmentPattern(text: string): { label: string; pattern: string; score: number } | null {
  const candidates: Array<{ label: string; pattern: string; score: number }> = [];
  for (const source of assignmentSources(text)) {
    for (const match of source.matchAll(/\b([A-Za-z][A-Za-z0-9_.:-]{2,79})\b\s*(=|:)\s*["']?([A-Za-z0-9_.:-]{2,80})["']?/g)) {
      const key = match[1] ?? "";
      const operator = match[2] ?? "";
      const value = match[3] ?? "";
      if (!isDistinctiveToken(key, true) || isBoringValue(value)) continue;
      const label = `${key}${operator}${value}`;
      candidates.push({
        label,
        pattern: `${escapeRegExp(key)}\\s*${escapeRegExp(operator)}\\s*["']?${escapeRegExp(value)}["']?`,
        score: label.length + assignmentContextScore(source, match.index ?? 0, match[0].length),
      });
    }
  }
  return candidates.sort((a, b) => b.score - a.score)[0] ?? null;
}

function assignmentContextScore(source: string, index: number, length: number): number {
  const before = source.slice(Math.max(0, index - 50), index).toLowerCase();
  const after = source.slice(index + length, Math.min(source.length, index + length + 50)).toLowerCase();
  const window = `${before} ${after}`;
  let score = 0;
  if (/\b(bad|failed|fails|broke|broken|wrong|avoid|forbid|forbidden|leaks?)\b/.test(after)) score += 50;
  if (/do\s+not|don't|never|should\s+not|must\s+not/.test(window)) score += 40;
  if (/\b(keep|instead|correct|right|use|prefer|allowed)\b/.test(before)) score -= 60;
  if (/\b(keep|instead|correct|right|use|prefer|allowed)\b/.test(after)) score -= 25;
  return score;
}

function assignmentSources(text: string): string[] {
  return [text];
}

function pickDistinctiveToken(text: string): string | null {
  const candidates = new Map<string, { raw: string; score: number }>();
  for (const match of text.matchAll(CODE_TOKEN_RE)) {
    const raw = (match[1] ?? match[2] ?? match[3] ?? "").trim();
    const token = raw.replace(/^[^\w.-]+|[^\w.-]+$/g, "");
    const isCodeLike = Boolean(match[1] ?? match[2]);
    if (!isDistinctiveToken(token, isCodeLike)) continue;
    const key = token.toLowerCase();
    const codeSpanBonus = match[1] ? 20 : match[2] ? 8 : 0;
    const shapeBonus =
      /[-_.:]/.test(token) ? 3 :
      /[A-Z]/.test(token.slice(1)) ? 2 :
      /\d/.test(token) ? 1 : 0;
    const score = token.length + codeSpanBonus + shapeBonus;
    const existing = candidates.get(key);
    if (!existing || score > existing.score) candidates.set(key, { raw: token, score });
  }
  const best = [...candidates.values()].sort((a, b) => b.score - a.score)[0];
  return best?.raw ?? null;
}

function isDistinctiveToken(token: string, isCodeLike: boolean): boolean {
  if (token.length < 4 || token.length > 80) return false;
  if (/^https?:\/\//i.test(token)) return false;
  if (/^\d+$/.test(token)) return false;
  const lower = token.toLowerCase();
  if (SENSOR_STOPWORDS.has(lower)) return false;
  if (!/[A-Za-z]/.test(token)) return false;
  const shaped = /[-_.:\d]/.test(token) || /[A-Z]/.test(token.slice(1));
  return shaped || isCodeLike;
}

function isBoringValue(value: string): boolean {
  if (!value || value.length > 80) return true;
  const lower = value.toLowerCase();
  if (lower === "true" || lower === "false") return false;
  return SENSOR_STOPWORDS.has(lower);
}

function sensorMessageFromBody(body: string, token: string): string {
  const instead = body.match(/\*\*Instead,\s*use:\*\*\s*([^\n]+)/i)?.[1]?.trim();
  if (instead) return `Avoid ${token}; ${instead}`;
  const firstGuidance = body
    .split("\n")
    .map((line) => line.replace(/^#+\s*/, "").trim())
    .find((line) => line.length > 0 && !line.startsWith("---"));
  return firstGuidance?.slice(0, 180) || `Avoid ${token}; this matched an autogenerated hAIve sensor.`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
