import type { Sensor } from "./types.js";

const CODE_TOKEN_RE = /`([^`\n]{3,80})`|["']([A-Za-z0-9_.:-]{3,80})["']|\b([A-Za-z][A-Za-z0-9_.:-]{2,79})\b/g;

const SENSOR_STOPWORDS = new Set([
  "about", "after", "again", "agent", "always", "anchor", "approach", "because",
  "before", "break", "broken", "cannot", "change", "code", "commit", "correct",
  "could", "default", "detect", "direct", "directory", "does", "error", "failed",
  "fails", "file", "files", "future", "instead", "memory", "never", "project",
  "recorded", "repo", "return", "should", "source", "status", "string", "this",
  "tried", "true", "type", "undefined", "value", "when", "where", "which", "with",
  "without",
]);

export interface SensorSuggestionOptions {
  /** Extra paths to put on the sensor. Defaults to the memory anchor paths. */
  paths?: string[];
}

/**
 * Conservatively suggest a regex sensor from a gotcha/attempt body.
 *
 * This helper intentionally returns null more often than it guesses. Autogenerated
 * sensors start as `warn`, never `block`; humans can promote them after seeing them fire.
 */
export function suggestSensorFromMemory(
  body: string,
  anchorPaths: string[],
  options: SensorSuggestionOptions = {},
): Sensor | null {
  const paths = options.paths ?? anchorPaths;
  if (paths.length === 0) return null;

  const negativeText = body.split(/\*\*Instead,\s*use:\*\*|^##\s+Instead\b/im)[0] ?? body;
  const token = pickDistinctiveToken(negativeText);
  if (!token) return null;

  return {
    kind: "regex",
    pattern: escapeRegExp(token),
    paths,
    message: sensorMessageFromBody(body, token),
    severity: "warn",
    autogen: true,
    last_fired: null,
  };
}

function pickDistinctiveToken(text: string): string | null {
  const candidates = new Map<string, { raw: string; score: number }>();
  for (const match of text.matchAll(CODE_TOKEN_RE)) {
    const raw = (match[1] ?? match[2] ?? match[3] ?? "").trim();
    const token = raw.replace(/^[^\w.-]+|[^\w.-]+$/g, "");
    const isCodeLike = Boolean(match[1] ?? match[2]);
    if (!isDistinctiveToken(token, isCodeLike)) continue;
    const key = token.toLowerCase();
    const codeSpanBonus = match[1] ? 20 : match[2] ? 8 : 0;
    const shapeBonus =
      /[-_.:]/.test(token) ? 3 :
      /[A-Z]/.test(token.slice(1)) ? 2 :
      /\d/.test(token) ? 1 : 0;
    const score = token.length + codeSpanBonus + shapeBonus;
    const existing = candidates.get(key);
    if (!existing || score > existing.score) candidates.set(key, { raw: token, score });
  }
  const best = [...candidates.values()].sort((a, b) => b.score - a.score)[0];
  return best?.raw ?? null;
}

function isDistinctiveToken(token: string, isCodeLike: boolean): boolean {
  if (token.length < 4 || token.length > 80) return false;
  if (/^https?:\/\//i.test(token)) return false;
  if (/^\d+$/.test(token)) return false;
  const lower = token.toLowerCase();
  if (SENSOR_STOPWORDS.has(lower)) return false;
  if (!/[A-Za-z]/.test(token)) return false;
  const shaped = /[-_.:\d]/.test(token) || /[A-Z]/.test(token.slice(1));
  return shaped || isCodeLike;
}

function sensorMessageFromBody(body: string, token: string): string {
  const instead = body.match(/\*\*Instead,\s*use:\*\*\s*([^\n]+)/i)?.[1]?.trim();
  if (instead) return `Avoid ${token}; ${instead}`;
  const firstGuidance = body
    .split("\n")
    .map((line) => line.replace(/^#+\s*/, "").trim())
    .find((line) => line.length > 0 && !line.startsWith("---"));
  return firstGuidance?.slice(0, 180) || `Avoid ${token}; this matched an autogenerated hAIve sensor.`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
